### ISSUE TITLE
How we solve k-s equation if we add one term ?

### ISSUE THREAD

**Issue by JingliangGao** [burakbudanur/ffmSlice#1]
Dear sir，
Thanks for sharing your code to help me solve standard k-s equation. But in my case, I need to add one term to the right-hand side of the equation, like
u_t = -uu_x - u_xx - u_xxxx + 3cos(2pi*x)

I am quite confused about ETDRK4 algorithm， so could you give me an advice about how to modify your code?

**Comment by burakbudanur** [comment]
For exponential time-differencing, the reference is [Kassam and Trefethen (2005)](https://people.maths.ox.ac.uk/trefethen/publication/PDF/2005_111.pdf) and the code at the end of this paper is likely to be clearer than mine. 

In any case, I believe you should be able to add your extra term to the computation of the nonlinear term in the physical space. You can write your equation in the following way: 

u_t = Lu + N(u) + F(x),

where the last term is the forcing, which for you is  3 cos (2pix). You should be able to add this term to the nonlinear term in physical or Fourier space.
